### ISSUE TITLE
RuntimeError: CUDA error: invalid argument

### ISSUE THREAD

**Issue by yxchng** [OpenGVLab/Vision-RWKV#7]
```
File "/home/user/segmentation/mmseg_custom/models/backbones/base/vrwkv.py", line 64, in backward
    gw = torch.sum(gw, dim=0)
RuntimeError: CUDA error: invalid argument
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

I am meeting this problem when trying to use your model on different datasets. Any idea why this might occur?

**Comment by duanduanduanyuchen** [comment]
> ```
> File "/home/user/segmentation/mmseg_custom/models/backbones/base/vrwkv.py", line 64, in backward
>     gw = torch.sum(gw, dim=0)
> RuntimeError: CUDA error: invalid argument
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> ```
> 
> I am meeting this problem when trying to use your model on different datasets. Any idea why this might occur?

I haven't seen this error before, but some Cuda errors may occur when out of memory.  Maybe you can try to reduce the batch size.

**Comment by Yueziyu** [comment]
请问最后这个问题解决了吗？我也遇到了相同的问题无法解决。如果解决了能麻烦您回复一下解决方法吗，谢谢

**Comment by Muzi010** [comment]
> 请问最后这个问题解决了吗？我也遇到了同样的问题无法解决。如果解决了可以麻烦您回复一下解决方法吗，谢谢

你是怎么解决的呀
